### ISSUE TITLE
Web hosting for docs

### ISSUE THREAD

**Issue by gopye** [nymtech/docs#1]
All documentation links are pointing to this repo, It would be great if viewing the docs didn't require running it locally.

**Comment by futurechimp** [comment]
Hi @gopye yep we just need to mess around with our hosting a little bit to make it happen. We were at EthBerlin all last week so still working on it.

**Comment by futurechimp** [comment]
This is now done. It's not yet linked publicly, but you can view the docs at https://nymtech.net/docs
