### ISSUE TITLE
Mixnode bonding/running/restarting logic

### ISSUE THREAD

**Issue by evgeny-garanin** [nymtech/docs#136]
Current design, approach on how to run a mixnode is built around assumption that you should have running, operational, routable mixnode before you "register" it in the mixnet with Bond action.

This seems to be an outdated measure as since the time it was implemented, we now have inactive mixnodes set, we have blacklist for mixnodes which are not routable.

On the counterpart, mixnode docs suggest you to Bond your mixnode before you actually Run it, which triggers WARN message in the mixnode logs. Same message will appear if you restart it (for example to apply changes made with describe command).

Proposed course of action:
1) remove WARN message from logs
OR
2) edit mixnode documents page to suggest Bonding only after you have set up your mixnode accordingly

**Comment by mfahampshire** [comment]
Passed comment to team and forgot to close this issue, apologies. I think option 1 is maybe the better way to go, since it affects restart after making changes with `describe` as well. I'll keep you updated. Many thanks for highlighting this.
