### ISSUE TITLE
Update latest stable version

### ISSUE THREAD

**Issue by RJ-Frosty** [nymtech/docs#150]
The docs say the latest stable version is Version: v1.0.1 (stable), and the precompiled binary are for ubuntu and other Debian systems.  As of June 9 v1.0.4 is the latest and Mac, windows binaries have been added.

**Comment by mfahampshire** [comment]
The main codebase is at 1.0.1, whereas the wallet is at 1.0.4. 

Which are you referring to?

**Comment by RJ-Frosty** [comment]
Didn't realize there is a difference.
