### ISSUE TITLE
Link to the doc into the readme is dead

### ISSUE THREAD

**Issue by L0GYKAL** [nymtech/docs#246]
**Describe the issue**
Link to the doc into the readme is dead

**Expected behaviour**
The link shouldn't be dead and it should bring me where it is supposed to

**Steps to Reproduce**
Go on the readme and click on the documentation links to build from source.

**Which area of Nym were you using?**
 - UI: Github
 - Browser: [Chrome (if applicable)]

**Comment by mfahampshire** [comment]
the link from the readme takes me to `https://nymtech.net/docs/stable/overview/` and looks fine to me, are you still having this problem?

**Comment by L0GYKAL** [comment]
yes, it seems to work now, but this link is still dead: `https://nymtech.net/docs/stable/nym-apps/wallet#for-developers`

**Comment by mfahampshire** [comment]
Where is ^ from?
