### ISSUE TITLE
Docs versioning

### ISSUE THREAD

**Issue by mfahampshire** [nymtech/docs#42]
cf. solidity docs versioning at bottom left of screen + warning. 

https://docs.soliditylang.org/en/v0.3.1/types.html

**Comment by futurechimp** [comment]
Yeah I like this idea. Especially as the network progresses, very useful.

**Comment by mfahampshire** [comment]
the secondary advantage of this is that we can treat certain versions as 'canonical' and then use them as the basis for translations as well

**Comment by mfahampshire** [comment]
closed in PR #65
