### ISSUE TITLE
index.md relative links fix

### ISSUE THREAD

**Issue by NodesGuru** [nymtech/docs#70]
Links on the index.md page are relative and only work if you are on the page
https://nymtech.net/docs/0.11.0/run-nym-nodes/index
([build instructions](build-nym))
([build instructions](validators))

If you end up on the page with trailing '/' links will lead to incorrect pages
https://nymtech.net/docs/0.11.0/run-nym-nodes/index/build-nym
https://nymtech.net/docs/0.11.0/run-nym-nodes/index/validators

So it should be either changed to absolute paths OR page with '/' in the end should redirect to the one without '/'

**Comment by NodesGuru** [comment]
I actually happens if you just follow the link https://nymtech.net/docs/0.11.0/run-nym-nodes/index
it will automatically open up in form
https://nymtech.net/docs/0.11.0/run-nym-nodes/index/

**Comment by mfahampshire** [comment]
fixed in #71 , thanks guys
